# Generated by Django 5.1 on 2024-09-01 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freetext",
            name="title",
        ),
    ]
