# Generated by Django 5.1 on 2024-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_rename_freetext_deneme"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
