# Generated by Django 5.1 on 2024-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_freetext"),
    ]

    operations = [
        migrations.AddField(
            model_name="freetext",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
